import { useState, useEffect } from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [dusjenKoster, settDusjenKoster] = useState(undefined);
  const KWh_forEnDusj = 6.5;
  const nettleie = 0.5;

  useEffect(() => {
    const idag = new Date();
    const dato = idag.toISOString().substr(0, 10);
    fetch(
      `https://norway-power.ffail.win/?zone=NO1&date=${idag
        .toISOString()
        .substr(0, 10)}`
    )
      .then(response => response.json())
      .then(data => {
        const timekey = dato + "T" + idag.getHours() + ":00:00+01:00";
        const timespris = data[timekey];

        settDusjenKoster(timespris.NOK_per_kWh * (KWh_forEnDusj + nettleie));
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>{`Hva koster en dusj?`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {dusjenKoster && (
          <h1
            className={styles.title}
          >{`Dusjen koster ${dusjenKoster.toLocaleString("no-NO")} kr`}</h1>
        )}
      </main>
    </div>
  );
}
